version: '2'
services:
  reports-app:
    image: reports
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://reports-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=reports
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8180:8180
  reports-mongodb:
    extends:
      file: mongodb.yml
      service: reports-mongodb
